@hostname = http://localhost:8080
@token =
@obraId =437ee5aa-75ef-4e88-958a-2369482bb009
@etapaId =
@funcionarioId =5dba14aa-681d-4f29-be01-4b4c9f1645c6
@funcionarioParaDeletarId =
@fornecedorId =9702a069-b0a6-4bf5-856d-fb65e1294d47
@materialId =4e0134c8-f965-40f0-9d83-a449447724cc
@materialId2 =
@orcamentoId =f800547b-b0d1-4869-bcde-4ed77ae26ae0
@apontamentoId = c1377600-6c9d-42cd-aaba-a85b5df3d217
###
# @name CadastrarFornecedorPrincipal
# 4. Cadastra o fornecedor principal.
POST {{hostname}}/fornecedores
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "nome": "Casa do Construtor Center",
    "cnpj": "12.345.678/0001-62",
    "contato": "Carlos Andrade",
    "email": "comercial@casadoconstrutor.com",
    "categoriaIds": [
        "311eb84a-bb34-483a-9bbd-505c2764f550"
    ]
}


######
# @name ListarFornecedores
# 4. Cadastra o fornecedor principal.

Get {{hostname}}/fornecedores
Content-Type: application/json
Cookie: jwt-token={{token}}


### 
# @name BusrcarPorID
GET {{hostname}}/fornecedores/{{fornecedorId}}
Content-Type: application/json
Cookie: jwt-token={{token}}

###



######
# @name CadastrarMaterial1
# 5. Cadastra o primeiro material.
POST {{hostname}}/materiais
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "nome": "Cimento Portland CP II 50kg",
    "descricao": "Cimento para uso geral.",
    "unidadeDeMedida": "saco",
    "categoria": "Estrutural"
}



### Cadastrar Fornecedor com Todos os Campos
POST {{hostname}}/fornecedores
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "nome": "Super Concreto",
    "cnpj": "55.666.777/0001-08",
    "contato": "Ana Lima",
    "email": "contato@superconcreto.com.br",
    "categoriaIds": [        "311eb84a-bb34-483a-9bbd-505c2764f550"
],
    "endereco": "Rua das Betoneiras, 123, Bairro Industrial",
    "avaliacao": 4.5,
    "observacoes": "Entrega sempre no prazo. Excelente qualidade."
}


### Atualizar Parcialmente um Fornecedor
PUT {{hostname}}/fornecedores/{{fornecedorId}}
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "nome": "Casa do Construtor Center Atualizado",
    "email": "comercial@casadoconstrutor.com",
    "contato": "Carlos Andrade Atualizado",
     "categoriaIds": [
        "311eb84a-bb34-483a-9bbd-505c2764f550"
    ]
}


### Deletar Fornecedor
DELETE {{hostname}}/fornecedores/{{fornecedorId}}
Content-Type: application/json
Cookie: jwt-token={{token}}