@hostname = http://localhost:8080
@token =
@obraId =45deec42-7f56-4713-a60e-0433e64c5abc
@etapaId =a894ec04-7fae-49f6-9d04-3714c8601bc8
@fornecedorId =aa6b21ea-8bb0-43f2-8453-829dfc41b084

@funcionarioId =
@funcionarioParaDeletarId =
@materialId =c4d089ac-95d4-4b66-a7f3-af914518396e
@orcamentoId =19b50d8a-333e-4829-8731-1235e3f0e55d
@apontamentoId = c1377600-6c9d-42cd-aaba-a85b5df3d217


###
# @name CriarOrcamentoPrincipal
# 10. Cria um orçamento para a etapa.
POST {{hostname}}/etapas/{{etapaId}}/orcamentos
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "fornecedorId": "{{fornecedorId}}",
    "itens": [
        {
            "nomeProduto": "Cimento Votoran CP II 50kg",
            "unidadeDeMedida": "saco",
            "categoria": "Cimento",
            "quantidade": 100,
            "valorUnitario": 55.50
        },
        {
            "nomeProduto": "Vergalhão de Aço CA-50 10mm",
            "unidadeDeMedida": "barra",
            "categoria": "Aço",
            "quantidade": 50,
            "valorUnitario": 120.00
        }
    ],
    "condicoesPagamento": "30 dias",
    "observacoes": "Material a ser entregue na obra B."
}
###
# @name AprovarOrcamento
# 11. Aprova o orçamento criado.
PATCH {{hostname}}/orcamentos/{{orcamentoId}}
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "status": "Aprovado"
}

###
# @name ListarTodosOrcamentos
# Lista todos os orçamentos com paginação padrão.
GET {{hostname}}/orcamentos?fornecedorId={{fornecedorId}}
Cookie: jwt-token={{token}}

####
# @name ListarOrcamentos

GET {{hostname}}/orcamentos
Cookie: jwt-token={{token}}



####
# @name ListarOrcamentos

GET {{hostname}}/orcamentos/{{orcamentoId}}
Cookie: jwt-token={{token}}


### Atualizar um Orçamento Completo
# @name atualizarOrcamento
PUT {{hostname}}/orcamentos/{{orcamentoId}}
Content-Type: application/json
Cookie: jwt-token={{token}}

{
    "fornecedorId": "aa6b21ea-8bb0-43f2-8453-829dfc41b084",
    "etapaId": "a894ec04-7fae-49f6-9d04-3714c8601bc8",
    "observacoes": "Orçamento  em 20/07/2025. Valores e quantidades atualizados.",
    "condicoesPagamento": "pix automatico",
    "itens": [
        {
            "nomeProduto": "Cimento CPII 50kg",
            "unidadeDeMedida": "saco",
            "categoria": "Cimento",
            "quantidade": 125,
            "valorUnitario": 58.00
        }
    ]
}